version: '3.8'
services:
  server:
    env_file:
      - env-release.env
    image: jpomdocker/jpom:server-${JPOM_VERSION}
    build:
      dockerfile: ./modules/server/Dockerfile
      context: .
      args:
        JPOM_VERSION: ${JPOM_VERSION}
    environment:
      "jpom.authorize.token": ${SERVER_TOKEN}
    volumes:
      - jpom-server-data:/usr/local/jpom-server/data
      - jpom-server-logs:/usr/local/jpom-server/logs
      - jpom-server-conf:/usr/local/jpom-server/conf
    ports:
      - "2122:2122"
volumes:
  jpom-server-data:
  jpom-server-logs:
  jpom-server-conf:
